// @flow

export default {
  ASYNC_STORAGE_ACKNOWLEDGE_FAILED_OPERATION: 'ASYNC_STORAGE_ACKNOWLEDGE_FAILED_OPERATION',

  ASYNC_STORAGE_WRITE_VALUE: 'ASYNC_STORAGE_WRITE_VALUE',
  ASYNC_STORAGE_WRITE_VALUE_SUCCEEDED: 'ASYNC_STORAGE_WRITE_VALUE_SUCCEEDED',
  ASYNC_STORAGE_WRITE_VALUE_FAILED: 'ASYNC_STORAGE_WRITE_VALUE_FAILED',
  ASYNC_STORAGE_WRITE_VALUE_IN_PROGRESS: 'ASYNC_STORAGE_WRITE_VALUE_IN_PROGRESS',
  ASYNC_STORAGE_ACKNOWLEDGE_WRITE_VALUE_OPERATION: 'ASYNC_STORAGE_ACKNOWLEDGE_WRITE_VALUE_OPERATION',

  ASYNC_STORAGE_READ_VALUE: 'ASYNC_STORAGE_READ_VALUE',
  ASYNC_STORAGE_READ_VALUE_SUCCEEDED: 'ASYNC_STORAGE_READ_VALUE_SUCCEEDED',
  ASYNC_STORAGE_READ_VALUE_FAILED: 'ASYNC_STORAGE_READ_VALUE_FAILED',
  ASYNC_STORAGE_READ_VALUE_IN_PROGRESS: 'ASYNC_STORAGE_READ_VALUE_IN_PROGRESS',
  ASYNC_STORAGE_ACKNOWLEDGE_READ_VALUE_OPERATION: 'ASYNC_STORAGE_ACKNOWLEDGE_READ_VALUE_OPERATION',
};
